# Apply a namespace to all *namespaced* resources
namespace: argocd
resources:
  - namespace.yaml
  - install.yaml

# If there are ClusterRoleBinding with ServiceAccount subjects
# missing the subject.namespace, patch them:
patches:
  - target:
      kind: ClusterRoleBinding
      name: argocd-application-controller
    patch: |
      - op: replace
        path: /subjects/0/namespace
        value: argocd

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: argocd
